import { Container, Grid, GridItem, Text, Button } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container centerContent>
          <Grid templateColumns="repeat(2, 1fr)" gap={6} p={4} boxShadow="md">
            <GridItem colSpan={2}>
              <Text
                as="h1"
                fontWeight={["normal", "normal", "bold"]}
                fontSize={["sm", "md", "lg"]}
              >
                Join our community
              </Text>
              <Text as="h2">30-day, hassle-free money</Text>
            </GridItem>
            <GridItem bg="teal.100">
              <Text color={"white"}>Monthly Subscription</Text>
              <Button>Sign Up</Button>
            </GridItem>
            <GridItem bg="teal.300">
              <Text color={"white"}>Why us</Text>
              <Text>Tutorials by industry experts</Text>
            </GridItem>
          </Grid>
        </Container>
      </main>
    </div>
  );
};

export default Home;
